apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
  app: webserver
  tier: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
      tier: webserver
    template:
      metadata:
        labels:
          app: webserver
          tier: webserver
      spec:
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80
